# https://taskfile.dev

version: "3"

vars:
  HUGO_VERSION: "0.115.0"
  HUGO_RELEASES: https://github.com/gohugoio/hugo/releases/download/

tasks:
  install:hugo:
    status:
      - test -f bin/hugo
    cmds:
      - mkdir -p bin
      - wget {{.HUGO_RELEASES}}v{{.HUGO_VERSION}}/hugo_extended_{{.HUGO_VERSION}}_{{OS}}-{{ARCH}}.tar.gz
      - defer: rm hugo_*.tar.gz
      - tar -xvf hugo_*.tar.gz -C bin
      - ./bin/hugo version

  install:theme:
    status:
      - test -d themes/PaperMod
    cmds:
      - git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

  install:
    desc: "Install all dependencies"
    cmds:
      - task: install:hugo
      - task: install:theme

  serve:
    desc: "Run dev server"
    deps:
      - install
    cmds:
      - ./bin/hugo server {{.CLI_ARGS}}

  build:
    desc: "Run dev server"
    deps:
      - install
    cmds:
      - ./bin/hugo {{.CLI_ARGS}}
